[package]
name = "song_load_rs"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "beatmap_load_bench"
harness = false

[[bench]]
name = "hash_bench"
harness = false

[lib]
name = "song_load_rs"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
bytes = "1.11.0"
sha1 = "0.10"
sha2 = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
zip = "7.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.11.0"
thiserror = "2"
symphonia = { version = "0.5", features = [
    "wav",
    "ogg",
    "opt-simd",
], default-features = false }
semver = { version = "1.0", features = ["serde"] }
regex = { version = "1.12.2", default-features = false, features = ["perf", "std", "unicode-perl"] }
ahash = { version = "0.8", features = ["serde"] }

# Android aarch64 dependencies
# [target.aarch64-linux-android.features]
[target.'cfg( target_os = "android" )'.dependencies]
paper2_tracing = { git = "https://github.com/Fernthedev/paperlog.git", package = "paper2_tracing", optional = true }

[features]
default = ["paper2-logging"]
paper2-logging = ["dep:paper2_tracing"]
throw_on_missing_data = []
# Allows loading full levels, including parsing beatmap data.
level-loading = []

[build-dependencies]
bindgen = "0.72"
cbindgen = "0.29"

[dev-dependencies]
criterion = "0.8"

[package.metadata.cbindgen.defines]
# Map the Cargo feature `level-loading` to a C macro so cbindgen
# will emit #ifdef guards in generated headers.
'feature = "level-loading"' = "LEVEL_LOADING"

[profile.release]
opt-level = 3
lto = true
